<a href="https://colab.research.google.com/github/mcgmed/Tensorflow/blob/main/TensorFlow_Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
mnist_data = tfds.load('fashion_mnist')
for item in mnist_data:
  print(item)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/60000 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/fashion_mnist/3.0.1.incompleteGXZ5ZL/fashion_mnist-train.tfrecord*...:   0%|  …

Generating test examples...:   0%|          | 0/10000 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/fashion_mnist/3.0.1.incompleteGXZ5ZL/fashion_mnist-test.tfrecord*...:   0%|   …

Dataset fashion_mnist downloaded and prepared to ~/tensorflow_datasets/fashion_mnist/3.0.1. Subsequent calls will reuse this data.
train
test


In [2]:
mnist_train = tfds.load(name="fashion_mnist", split="train")
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>


In [3]:
for item in mnist_train.take(1):
  print(type(item))
  print(item.keys())

<class 'dict'>
dict_keys(['image', 'label'])


In [4]:
for item in mnist_train.take(1):
  print(type(item))
  print(item.keys())
  print(item['image'])
  print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


In [5]:
mnist_test, info = tfds.load(name="fashion_mnist", with_info="true")
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_path='~/tensorflow_datasets/fashion_mnist/3.0.1',
    file_format=tfrecord,
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
      author  

### **Using TFDS with Keras Models**



In [6]:
mnist = tf.keras.datasets.fashion_mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()

4422102/4422102 [==============================] - 0s 0us/step


When using TFDS the code is very similar, but with some minor changes. The Keras
datasets gave us ndarray types that worked natively in model.fit, but with TFDS
we’ll need to do a little conversion work:

In [7]:
(training_images, training_labels), (test_images, test_labels) = tfds.as_numpy(tfds.load('fashion_mnist', split = ['train', 'test'], batch_size=-1, as_supervised=True))

Using **tfds.as_numpy** in the call to tfds.load causes them to be returned as Numpy arrays. Specifying **batch_size=-1** gives us all of the data, and **as_supervised=True** ensures we get tuples of (input, label) returned.

In [8]:
training_images.shape

(60000, 28, 28, 1)

In [9]:
import tensorflow as tf
import tensorflow_datasets as tfds

(training_images, training_labels), (test_images, test_labels) = tfds.as_numpy(tfds.load('fashion_mnist', split = ['train', 'test'], batch_size=-1, as_supervised=True))

training_images = training_images / 255.0
test_images = test_images / 255.0

model = tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28,1)),
                                    tf.keras.layers.Dense(128, activation=tf.nn.relu),
                                    tf.keras.layers.Dropout(0.2),
                                    tf.keras.layers.Dense(10, activation=tf.nn.softmax)])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 2ms/step - loss: 0.5325 - accuracy: 0.8112
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.4026 - accuracy: 0.8535
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3670 - accuracy: 0.8655
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3458 - accuracy: 0.8739
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3306 - accuracy: 0.8781


### Horse or Human

Only train part of the dataset has chosen.

The data is batched and shuffled to make training more effective.

In [10]:
data = tfds.load('horses_or_humans', split='train', as_supervised=True)
train_batches = data.shuffle(100).batch(10)

model = tf.keras.models.Sequential([tf.keras.layers.Conv2D(16, (3,3), activation='relu',input_shape=(300, 300, 3)),
                                    tf.keras.layers.MaxPooling2D(2, 2),
                                    tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
                                    tf.keras.layers.MaxPooling2D(2,2),
                                    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
                                    tf.keras.layers.MaxPooling2D(2,2),
                                    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
                                    tf.keras.layers.MaxPooling2D(2,2),
                                    tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
                                    tf.keras.layers.MaxPooling2D(2,2),
                                    tf.keras.layers.Flatten(),
                                    tf.keras.layers.Dense(512, activation='relu'),
                                    tf.keras.layers.Dense(1, activation='sigmoid')])

model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])

history = model.fit(train_batches, epochs=5)

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating train examples...:   0%|          | 0/1027 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/horses_or_humans/3.0.0.incompleteYGXRPT/horses_or_humans-train.tfrecord*...:  …

Generating test examples...:   0%|          | 0/256 [00:00<?, ? examples/s]

Shuffling ~/tensorflow_datasets/horses_or_humans/3.0.0.incompleteYGXRPT/horses_or_humans-test.tfrecord*...:   …

Dataset horses_or_humans downloaded and prepared to ~/tensorflow_datasets/horses_or_humans/3.0.0. Subsequent calls will reuse this data.
Epoch 1/5
103/103 [==============================] - 11s 39ms/step - loss: 2.4595 - accuracy: 0.8481
Epoch 2/5
103/103 [==============================] - 2s 18ms/step - loss: 0.0758 - accuracy: 0.9766
Epoch 3/5
103/103 [==============================] - 2s 18ms/step - loss: 0.0734 - accuracy: 0.9766
Epoch 4/5
103/103 [==============================] - 2s 18ms/step - loss: 0.3244 - accuracy: 0.8958
Epoch 5/5
103/103 [==============================] - 2s 18ms/step - loss: 0.4741 - accuracy: 0.7809


if you want to do validation of your model while training, you can do so by loading a separate validation set from TFDS like this:

In [11]:
val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)
validation_batches = val_data.batch(32)
history = model.fit(train_batches, epochs=10, validation_data=validation_batches)

Epoch 1/10
103/103 [==============================] - 3s 27ms/step - loss: 0.4154 - accuracy: 0.8130 - val_loss: 0.8765 - val_accuracy: 0.8320
Epoch 2/10
103/103 [==============================] - 2s 20ms/step - loss: 0.2673 - accuracy: 0.9036 - val_loss: 0.8342 - val_accuracy: 0.8750
Epoch 3/10
103/103 [==============================] - 2s 21ms/step - loss: 0.0900 - accuracy: 0.9698 - val_loss: 1.1552 - val_accuracy: 0.8906
Epoch 4/10
103/103 [==============================] - 3s 25ms/step - loss: 0.0429 - accuracy: 0.9834 - val_loss: 0.7981 - val_accuracy: 0.8867
Epoch 5/10
103/103 [==============================] - 2s 20ms/step - loss: 0.0090 - accuracy: 0.9981 - val_loss: 1.4035 - val_accuracy: 0.8984
Epoch 6/10
103/103 [==============================] - 2s 19ms/step - loss: 9.8615e-04 - accuracy: 1.0000 - val_loss: 1.7148 - val_accuracy: 0.8945
Epoch 7/10
103/103 [==============================] - 2s 19ms/step - loss: 3.5758e-04 - accuracy: 1.0000 - val_loss: 1.8184 - val_accuracy